/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface BootstrapStatic {
  events?: {
    id?: number;
    name?: string;
    deadline_time?: string;
    average_entry_score?: number;
    finished?: boolean;
    data_checked?: boolean;
    highest_scoring_entry?: null;
    deadline_time_epoch?: number;
    deadline_time_game_offset?: number;
    highest_score?: null;
    is_previous?: boolean;
    is_current?: boolean;
    is_next?: boolean;
    chip_plays?: {
      chip_name?: string;
      num_played?: number;
      [k: string]: any;
    }[];
    most_selected?: number | null;
    most_transferred_in?: number | null;
    top_element?: number | null;
    transfers_made?: number;
    most_captained?: number | null;
    most_vice_captained?: number | null;
    [k: string]: any;
  }[];
  game_settings?: {
    league_join_private_max?: number;
    league_join_public_max?: number;
    league_max_size_public_classic?: number;
    league_max_size_public_h2h?: number;
    league_max_size_private_h2h?: number;
    league_max_ko_rounds_private_h2h?: number;
    league_prefix_public?: string;
    league_points_h2h_win?: number;
    league_points_h2h_lose?: number;
    league_points_h2h_draw?: number;
    squad_squadplay?: number;
    squad_squadsize?: number;
    squad_team_limit?: number;
    squad_total_spend?: number;
    ui_currency_multiplier?: number;
    ui_use_special_shirts?: boolean;
    ui_special_shirt_exclusions?: any[];
    stats_form_days?: number;
    sys_vice_captain_enabled?: boolean;
    transfers_sell_on_fee?: number;
    cup_start_event_id?: number;
    timezone?: string;
    [k: string]: any;
  };
  phases?: {
    id?: number;
    name?: string;
    start_event?: number;
    stop_event?: number;
    [k: string]: any;
  }[];
  teams?: {
    code?: number;
    draw?: number;
    form?: null;
    id?: number;
    loss?: number;
    name?: string;
    played?: number;
    points?: number;
    position?: number;
    short_name?: string;
    strength?: number;
    team_division?: null;
    unavailable?: boolean;
    win?: number;
    strength_overall_home?: number;
    strength_overall_away?: number;
    strength_attack_home?: number;
    strength_attack_away?: number;
    strength_defence_home?: number;
    strength_defence_away?: number;
    [k: string]: any;
  }[];
  total_players?: number;
  elements?: {
    chance_of_playing_next_round?: null | number;
    chance_of_playing_this_round?: null | number;
    code?: number;
    cost_change_event?: number;
    cost_change_event_fall?: number;
    cost_change_start?: number;
    cost_change_start_fall?: number;
    dreamteam_count?: number;
    element_type?: number;
    ep_next?: string;
    ep_this?: string;
    event_points?: number;
    first_name?: string;
    form?: string;
    id?: number;
    in_dreamteam?: boolean;
    news?: string;
    news_added?: null | string;
    now_cost?: number;
    photo?: string;
    points_per_game?: string;
    second_name?: string;
    selected_by_percent?: string;
    special?: boolean;
    squad_number?: null;
    status?: string;
    team?: number;
    team_code?: number;
    total_points?: number;
    transfers_in?: number;
    transfers_in_event?: number;
    transfers_out?: number;
    transfers_out_event?: number;
    value_form?: string;
    value_season?: string;
    web_name?: string;
    minutes?: number;
    goals_scored?: number;
    assists?: number;
    clean_sheets?: number;
    goals_conceded?: number;
    own_goals?: number;
    penalties_saved?: number;
    penalties_missed?: number;
    yellow_cards?: number;
    red_cards?: number;
    saves?: number;
    bonus?: number;
    bps?: number;
    influence?: string;
    creativity?: string;
    threat?: string;
    ict_index?: string;
    [k: string]: any;
  }[];
  element_stats?: {
    label?: string;
    name?: string;
    [k: string]: any;
  }[];
  element_types?: {
    id?: number;
    plural_name?: string;
    plural_name_short?: string;
    singular_name?: string;
    singular_name_short?: string;
    squad_select?: number;
    squad_min_play?: number;
    squad_max_play?: number;
    ui_shirt_specific?: boolean;
    sub_positions_locked?: number[];
    [k: string]: any;
  }[];
  [k: string]: any;
}
