/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ElementSummary {
  fixtures?: {
    code?: number;
    team_h?: number;
    team_h_score?: null;
    team_a?: number;
    team_a_score?: null;
    event?: number;
    finished?: boolean;
    minutes?: number;
    provisional_start_time?: boolean;
    kickoff_time?: string;
    event_name?: string;
    is_home?: boolean;
    difficulty?: number;
    [k: string]: any;
  }[];
  history?: {
    element?: number;
    fixture?: number;
    opponent_team?: number;
    total_points?: number;
    was_home?: boolean;
    kickoff_time?: string;
    team_h_score?: number;
    team_a_score?: number;
    round?: number;
    minutes?: number;
    goals_scored?: number;
    assists?: number;
    clean_sheets?: number;
    goals_conceded?: number;
    own_goals?: number;
    penalties_saved?: number;
    penalties_missed?: number;
    yellow_cards?: number;
    red_cards?: number;
    saves?: number;
    bonus?: number;
    bps?: number;
    influence?: string;
    creativity?: string;
    threat?: string;
    ict_index?: string;
    value?: number;
    transfers_balance?: number;
    selected?: number;
    transfers_in?: number;
    transfers_out?: number;
    [k: string]: any;
  }[];
  history_past?: {
    season_name?: string;
    element_code?: number;
    start_cost?: number;
    end_cost?: number;
    total_points?: number;
    minutes?: number;
    goals_scored?: number;
    assists?: number;
    clean_sheets?: number;
    goals_conceded?: number;
    own_goals?: number;
    penalties_saved?: number;
    penalties_missed?: number;
    yellow_cards?: number;
    red_cards?: number;
    saves?: number;
    bonus?: number;
    bps?: number;
    influence?: string;
    creativity?: string;
    threat?: string;
    ict_index?: string;
    [k: string]: any;
  }[];
  [k: string]: any;
}
