/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ElementSummary {
  fixtures?: {
    code?: number;
    teamH?: number;
    teamHScore?: null;
    teamA?: number;
    teamAScore?: null;
    event?: number;
    finished?: boolean;
    minutes?: number;
    provisionalStartTime?: boolean;
    kickoffTime?: string;
    eventName?: string;
    isHome?: boolean;
    difficulty?: number;
    [k: string]: any;
  }[];
  history?: {
    element?: number;
    fixture?: number;
    opponentTeam?: number;
    totalPoints?: number;
    wasHome?: boolean;
    kickoffTime?: string;
    teamHScore?: number;
    teamAScore?: number;
    round?: number;
    minutes?: number;
    goalsScored?: number;
    assists?: number;
    cleanSheets?: number;
    goalsConceded?: number;
    ownGoals?: number;
    penaltiesSaved?: number;
    penaltiesMissed?: number;
    yellowCards?: number;
    redCards?: number;
    saves?: number;
    bonus?: number;
    bps?: number;
    influence?: string;
    creativity?: string;
    threat?: string;
    ictIndex?: string;
    value?: number;
    transfersBalance?: number;
    selected?: number;
    transfersIn?: number;
    transfersOut?: number;
    [k: string]: any;
  }[];
  historyPast?: {
    seasonName?: string;
    elementCode?: number;
    startCost?: number;
    endCost?: number;
    totalPoints?: number;
    minutes?: number;
    goalsScored?: number;
    assists?: number;
    cleanSheets?: number;
    goalsConceded?: number;
    ownGoals?: number;
    penaltiesSaved?: number;
    penaltiesMissed?: number;
    yellowCards?: number;
    redCards?: number;
    saves?: number;
    bonus?: number;
    bps?: number;
    influence?: string;
    creativity?: string;
    threat?: string;
    ictIndex?: string;
    [k: string]: any;
  }[];
  [k: string]: any;
}
