/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Entry {
  id?: number;
  joinedTime?: string;
  startedEvent?: number;
  favouriteTeam?: null;
  playerFirstName?: string;
  playerLastName?: string;
  playerRegionId?: number;
  playerRegionName?: string;
  playerRegionIsoCodeShort?: string;
  playerRegionIsoCodeLong?: string;
  summaryOverallPoints?: number;
  summaryOverallRank?: number;
  summaryEventPoints?: number;
  summaryEventRank?: number;
  currentEvent?: number;
  leagues?: {
    classic?: {
      id?: number;
      name?: string;
      shortName?: string | null;
      created?: string;
      closed?: boolean;
      rank?: null;
      maxEntries?: null;
      leagueType?: string;
      scoring?: string;
      adminEntry?: null | number;
      startEvent?: number;
      entryRank?: number;
      entryLastRank?: number;
      entryCanLeave?: boolean;
      entryCanAdmin?: boolean;
      entryCanInvite?: boolean;
      [k: string]: any;
    }[];
    h2h?: any[];
    [k: string]: any;
  };
  name?: string;
  kit?: null;
  lastDeadlineBank?: number;
  lastDeadlineValue?: number;
  lastDeadlineTotalTransfers?: number;
  [k: string]: any;
}
