/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Entry {
  id?: number;
  joined_time?: string;
  started_event?: number;
  favourite_team?: null;
  player_first_name?: string;
  player_last_name?: string;
  player_region_id?: number;
  player_region_name?: string;
  player_region_iso_code_short?: string;
  player_region_iso_code_long?: string;
  summary_overall_points?: number;
  summary_overall_rank?: number;
  summary_event_points?: number;
  summary_event_rank?: null;
  current_event?: number;
  leagues?: {
    classic?: {
      id?: number;
      name?: string;
      short_name?: string | null;
      created?: string;
      closed?: boolean;
      rank?: null;
      max_entries?: null;
      league_type?: string;
      scoring?: string;
      admin_entry?: null | number;
      start_event?: number;
      entry_rank?: number;
      entry_last_rank?: number;
      entry_can_leave?: boolean;
      entry_can_admin?: boolean;
      entry_can_invite?: boolean;
      [k: string]: any;
    }[];
    h2h?: any[];
    [k: string]: any;
  };
  name?: string;
  kit?: null;
  [k: string]: any;
}
