/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface EntryPicks {
  active_chip?: null;
  automatic_subs?: {
    entry?: number;
    element_in?: number;
    element_out?: number;
    event?: number;
    [k: string]: any;
  }[];
  entry_history?: {
    event?: number;
    points?: number;
    total_points?: number;
    rank?: number;
    rank_sort?: number;
    overall_rank?: number;
    bank?: number;
    value?: number;
    event_transfers?: number;
    event_transfers_cost?: number;
    points_on_bench?: number;
    [k: string]: any;
  };
  picks?: {
    element?: number;
    position?: number;
    multiplier?: number;
    is_captain?: boolean;
    is_vice_captain?: boolean;
    [k: string]: any;
  }[];
  [k: string]: any;
}
