/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface EventLive {
  fixtures?: {
    id?: number;
    kickoffTimeFormatted?: string;
    started?: boolean;
    eventDay?: number;
    deadlineTime?: string;
    deadlineTimeFormatted?: string;
    stats?: (
      | {
          /**
           * This interface was referenced by `undefined`'s JSON-Schema definition
           * via the `patternProperty` "^(+)+$".
           */
          [k: string]: {
            a?: {
              value?: number;
              element?: number;
              [k: string]: any;
            }[];
            h?: {
              value?: number;
              element?: number;
              [k: string]: any;
            }[];
            [k: string]: any;
          };
        }
      | {
          /**
           * This interface was referenced by `undefined`'s JSON-Schema definition
           * via the `patternProperty` "^(+)+$".
           */
          [k: string]: {
            /**
             * This interface was referenced by `undefined`'s JSON-Schema definition
             * via the `patternProperty` "^(+)+$".
             */
            [k: string]: any[];
          };
        }
      | {
          /**
           * This interface was referenced by `undefined`'s JSON-Schema definition
           * via the `patternProperty` "^(+)+$".
           */
          [k: string]: {
            /**
             * This interface was referenced by `undefined`'s JSON-Schema definition
             * via the `patternProperty` "^(+)+$".
             */
            [k: string]: {
              value?: number;
              element?: number;
              [k: string]: any;
            }[];
          };
        })[];
    code?: number;
    kickoffTime?: string;
    teamHScore?: number;
    teamAScore?: number;
    finished?: boolean;
    minutes?: number;
    provisionalStartTime?: boolean;
    finishedProvisional?: boolean;
    event?: number;
    teamA?: number;
    teamH?: number;
    [k: string]: any;
  }[];
  elements?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^(+)+$".
     */
    [k: string]: {
      explain?: (
        | {
            /**
             * This interface was referenced by `undefined`'s JSON-Schema definition
             * via the `patternProperty` "^(+)+$".
             */
            [k: string]: {
              points?: number;
              name?: string;
              value?: number;
              [k: string]: any;
            };
          }
        | number)[][];
      stats?: {
        yellowCards?: number;
        ownGoals?: number;
        creativity?: number;
        goalsConceded?: number;
        bonus?: number;
        redCards?: number;
        saves?: number;
        influence?: number;
        bps?: number;
        cleanSheets?: number;
        assists?: number;
        ictIndex?: number;
        goalsScored?: number;
        threat?: number;
        penaltiesMissed?: number;
        totalPoints?: number;
        penaltiesSaved?: number;
        inDreamteam?: boolean;
        minutes?: number;
        [k: string]: any;
      };
      [k: string]: any;
    };
  };
  [k: string]: any;
}
