/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface EventLive {
  elements?: {
    id?: number;
    stats?: {
      minutes?: number;
      goalsScored?: number;
      assists?: number;
      cleanSheets?: number;
      goalsConceded?: number;
      ownGoals?: number;
      penaltiesSaved?: number;
      penaltiesMissed?: number;
      yellowCards?: number;
      redCards?: number;
      saves?: number;
      bonus?: number;
      bps?: number;
      influence?: string;
      creativity?: string;
      threat?: string;
      ictIndex?: string;
      totalPoints?: number;
      inDreamteam?: boolean;
      [k: string]: any;
    };
    explain?: {
      fixture?: number;
      stats?: {
        identifier?: string;
        points?: number;
        value?: number;
        [k: string]: any;
      }[];
      [k: string]: any;
    }[];
    [k: string]: any;
  }[];
  [k: string]: any;
}
